# Generated by Django 5.0.6 on 2024-08-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AddField(
            model_name='expenses',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
