# Generated by Django 5.0.6 on 2024-10-01 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('expenses', '0003_currencies_expenses_currency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Expense',
        ),
        migrations.DeleteModel(
            name='Currencies',
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency', to='common.currency'),
        ),
    ]
