# Generated by Django 5.0.2 on 2024-10-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_currency_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
    ]
